// server/seo/executors/internalLink.ts
import { db } from "../../db";
import { seoLinks } from "../../../shared/schema";
import { logger } from "../../lib/logger";

export async function addInternalLink(action: {
  page: string;
  details: string;
  hypothesis: string;
  campaignId: number | null;
}): Promise<{ previousValue: string; newValue: string }> {
  // Parse details - expected format: "from: /page-a\nto: /page-b\nanchor: click here"
  const lines = action.details.split("\n");
  let fromPage = action.page;
  let toPage = "";
  let anchorText = "";

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.toLowerCase().startsWith("from:")) {
      fromPage = trimmed.slice("from:".length).trim() || action.page;
    } else if (trimmed.toLowerCase().startsWith("to:")) {
      toPage = trimmed.slice("to:".length).trim();
    } else if (trimmed.toLowerCase().startsWith("anchor:")) {
      anchorText = trimmed.slice("anchor:".length).trim();
    }
  }

  if (!toPage || !anchorText) {
    throw new Error(`Invalid link format. Expected "to: ...\nanchor: ...". Got: ${action.details}`);
  }

  await db.insert(seoLinks).values({
    fromPage,
    toPage,
    anchorText,
    context: action.hypothesis,
    autoGenerated: true,
    active: true,
  });

  logger.info(`[SEO:Link] Added internal link ${fromPage} -> ${toPage}`);

  return { previousValue: "", newValue: `${fromPage} -> ${toPage} [${anchorText}]` };
}
